[build]
command = "yarn build"
functions = "functions/"

[[plugins]]
package = "netlify-plugin-gatsby-cache"

[[redirects]]
from = "/reference/tools-and-interfaces/prisma-schema/prisma-schema-file"
to = "/reference/tools-and-interfaces/prisma-schema"
status = 301

[[redirects]]
from = "/reference/tools-and-interfaces/prisma-client/api"
to = "/reference/tools-and-interfaces/prisma-client"
status = 301



